rails_tut_url: "https://www.railstutorial.org"
rails_tut_help: "http://www.railstutorial.org/help"
rails_tut_book: "http://www.railstutorial.org/book"
learn_enough: "https://www.learnenough.com/"
screen_cast: "https://screencasts.railstutorial.org/"
rails_url: "https://rubyonrails.org/"
rails_contact_url: "https://www.railstutorial.org/contact"
